spring:
  application:
    name: tracking-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/trackingdb}
    username: ${SPRING_DATASOURCE_USERNAME:activityual}
    password: ${SPRING_DATASOURCE_PASSWORD:activityual}
  jpa:
    hibernate: { ddl-auto: validate }
    open-in-view: false
  flyway: { enabled: true, baseline-on-migrate: true }
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

server: { port: 8083 }
outbox: { relay-ms: 2000 }
management:
  endpoints:
    web: { exposure: { include: health,info,prometheus } }
springdoc:
  swagger-ui: { path: /swagger }

