nameOverride: gateway-service
image: { repository: REPLACE_ME_ECR/activityual/gateway-service, tag: latest }
service: { port: 80, targetPort: 8080 }
config:
  SPRING_RABBITMQ_HOST: rabbitmq.platform.svc.cluster.local
  SPRING_RABBITMQ_PORT: "5672"
  AUTH_URL: http://auth-service
  ACTIVITY_URL: http://activity-service
  TRACKING_URL: http://tracking-service
  ANALYTICS_URL: http://analytics-service
  COACH_URL: http://coach-service
  RECO_URL: http://recommendation-service
  NOTIF_URL: http://notification-service
secrets:
  PLACEHOLDER: "unused"
extraEnvFromSecrets:
  - activityual-shared
ingress:
  enabled: true
  className: alb
  path: /
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
