nameOverride: notification-service
image:
  repository: REPLACE_ME_ECR/activityual/notification-service
  tag: latest
service:
  port: 80
  targetPort: 8087
config:
  SPRING_RABBITMQ_HOST: rabbitmq.platform.svc.cluster.local
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_DATASOURCE_URL: jdbc:postgresql://activityual-rds.cgfueeqgoqyo.us-east-1.rds.amazonaws.com:5432/notifdb
  SPRING_DATASOURCE_USERNAME: activityual
secrets:
  PLACEHOLDER: "unused"
extraEnvFromSecrets:
  - activityual-shared
