nameOverride: recommendation-service
image:
  repository: REPLACE_ME_ECR/activityual/recommendation-service
  tag: latest
service:
  port: 80
  targetPort: 8086
config:
  RABBIT_HOST: rabbitmq.platform.svc.cluster.local
  RABBIT_PORT: "5672"
  SPRING_DATASOURCE_URL: jdbc:postgresql://activityual-rds.cluster-x.us-east-1.rds.amazonaws.com:5432/recommendationdb
  SPRING_DATASOURCE_USERNAME: activityual
secrets:
  JWT_SECRET: "change-me-please-change-me-please-32bytes!!"
  SPRING_DATASOURCE_PASSWORD: "REPLACE_ME"
probes:
  enabled: true
  path: /actuator/health
  initialDelaySeconds: 45
  periodSeconds: 10
